---
name:

logging:
  level: INFO

dir:

network:
  type: dynamic
  label: private
  cloud_properties: {}

env:
  bosh:
    password:

resources:
  persistent_disk: 4096
  cloud_properties:
    instance_type: 'Small Type'
    availability_zone:

cloud:
  plugin: cloudstack
  properties:
    cloudstack:
      cloudstack_host: 168.1.43.14
      cloudstack_port: 8080
      cloudstack_api_key: hHdIgGdz6V-6I9Dc0dqhgUKutGJX-7_XTurvjd89SWAXPFiMZEy_Gb0uGfzbTyzS1rrdcwwZq81nxWS3UW8IcQ
      cloudstack_secret_access_key: zKao312dFgDKFdSI04Kh2axSuiWDXLDXj848GFxXRvRZPjiEuA6UfQq4uGdEHxrvuaYoNpv3_SBWfRqX6lPIwg
      cloudstack_scheme: http
      default_security_groups: ["default"]
    registry:
      endpoint: http://admin:admin@localhost:25889
      user: admin
      password: admin
    stemcell:
      kernel_id:
      disk: 4096
    agent:
      ntp: []
      blobstore:
        plugin: local
        properties:
          blobstore_path: /var/vcap/micro_bosh/data/cache
      mbus:

apply_spec:
  properties: {}
  agent:
    blobstore: {}
    nats: {}
